Repository GoogleChromeLabs/chromeos_smart_card_connector, pull requests merged in 2020-06, with the labels that each got.

#117 Fix PIP installation in webports
  third_party/webports/src/src/build_tools/pip_install.sh
Labels: bug

#118 Use the pinned webports repository
  env/constants.sh
  env/initialize.sh
  third_party/webports/README.google
Labels: bug

#119 Workaround for NaCl init issue on desktops
  common/make/nacl_module_building_common.mk
  env/.gitignore
Labels: enhancement

#120 Fix the headers in the NaCl code test launcher UI
  common/tests_runner/src/index.html
Labels: bug

#124 Fix cert validation failures in NaCl SDK initialization
  README.rst
  third_party/nacl_sdk/nacl_sdk/sdk_tools/cacerts.txt
  third_party/nacl_sdk/nacl_sdk/sdk_tools/download.py
  third_party/nacl_sdk/nacl_sdk/sdk_tools/third_party/__init__.py
  third_party/nacl_sdk/nacl_sdk/sdk_tools/third_party/fancy_urllib/README.chromium
  third_party/nacl_sdk/nacl_sdk/sdk_tools/third_party/fancy_urllib/__init__.py
Labels: bug

#126 Extract PC/SC-based reader status tracker
  third_party/pcsc-lite/naclport/js_client/src/reader-tracker-through-pcsc-api.js
  third_party/pcsc-lite/naclport/server/src/reader-tracker.js
Labels: enhancement

#131 Add help button
  smart_card_connector_app/src/_locales/en/messages.json
  smart_card_connector_app/src/manifest.json.template
  smart_card_connector_app/src/window-help-showing.js
  smart_card_connector_app/src/window-main.js
  smart_card_connector_app/src/window.html
Labels: enhancement

#134 Add comment for passed readerTracker methods
  smart_card_connector_app/src/window-devices-displaying.js
Labels: enhancement, refactoring
