Repository GoogleChromeLabs/chromeos_smart_card_connector, pull requests merged in 2021-11, with the labels that each got.

#422 Fix JS minification issues
  common/js/src/logging/log-buffer.js
  smart_card_connector_app/src/window-logs-exporting.js
  third_party/pcsc-lite/naclport/server/src/reader-tracker.js
Labels: bug

#421 Refactor methods in ipc_emulation
  common/cpp/src/google_smart_card_common/cpp_attributes.h
  common/cpp/src/google_smart_card_common/ipc_emulation.cc
  common/cpp/src/google_smart_card_common/ipc_emulation.h
  third_party/pcsc-lite/naclport/server/src/google_smart_card_pcsc_lite_server/global.cc
  third_party/pcsc-lite/naclport/server/src/winscard_msg_nacl.cc
Labels: refactoring

#426 Fix IPC emulation waiting with no timeout
  common/cpp/src/google_smart_card_common/ipc_emulation.cc
Labels: bug

#428 Pass --bind only to the Emscripten linker
  common/make/internal/executable_building_emscripten.mk
Labels: enhancement

#427 Emulate pipe() IPC function
  common/cpp/build/tests/Makefile
  common/cpp/src/google_smart_card_common/ipc_emulation.cc
  common/cpp/src/google_smart_card_common/ipc_emulation.h
  third_party/pcsc-lite/naclport/server/build/Makefile
  third_party/pcsc-lite/naclport/server/src/winscard_msg_nacl.cc
Labels: enhancement

#431 Add tests for ipc_emulation
  common/cpp/src/google_smart_card_common/ipc_emulation_unittest.cc
Labels: enhancement

#430 [usb] Rename LibusbOverChromeUsbGlobal
  smart_card_connector_app/build/executable_module/Makefile
  smart_card_connector_app/src/application.cc
  smart_card_connector_app/src/application.h
  third_party/libusb/webport/build/Makefile
  third_party/libusb/webport/src/public/libusb_web_port_service.cc
  third_party/libusb/webport/src/public/libusb_web_port_service.h
Labels: refactoring

#432 [usb] Rename LibusbOverChromeUsb
  third_party/libusb/webport/build/Makefile
  third_party/libusb/webport/build/tests/Makefile
  third_party/libusb/webport/src/libusb_js_proxy.cc
  third_party/libusb/webport/src/libusb_js_proxy.h
  third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
  third_party/libusb/webport/src/public/libusb_web_port_service.cc
  third_party/libusb/webport/src/public/libusb_web_port_service.h
  third_party/libusb/webport/src/usb_transfers_parameters_storage.h
Labels: refactoring

#433 [usb] Add JsProxyReceiver
  smart_card_connector_app/src/background.js
  third_party/libusb/webport/src/chrome_usb/api_bridge.h
  third_party/libusb/webport/src/chrome_usb/chrome-usb-backend.js
  third_party/libusb/webport/src/libusb-proxy-receiver.js
Labels: enhancement

#436 [wasm] Fix&enable multi-threading in tests
  common/cpp/src/google_smart_card_common/messaging/typed_message_router_unittest.cc
  common/cpp/src/google_smart_card_common/requesting/async_request_unittest.cc
  common/cpp/src/google_smart_card_common/requesting/async_requests_storage_unittest.cc
  common/cpp_unit_test_runner/src/build_emscripten.mk
  third_party/googletest/webport/build/Makefile
  third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
Labels: enhancement

#434 Rename Detach() to ShutDown()
  common/cpp/src/google_smart_card_common/global_context.h
  common/cpp/src/google_smart_card_common/global_context_impl_emscripten.cc
  common/cpp/src/google_smart_card_common/global_context_impl_emscripten.h
  common/cpp/src/google_smart_card_common/global_context_impl_nacl.cc
  common/cpp/src/google_smart_card_common/global_context_impl_nacl.h
  common/cpp/src/google_smart_card_common/requesting/js_request_receiver.cc
  common/cpp/src/google_smart_card_common/requesting/js_request_receiver.h
  common/cpp/src/google_smart_card_common/requesting/js_requester.cc
  common/cpp/src/google_smart_card_common/requesting/js_requester.h
  common/cpp/src/google_smart_card_common/requesting/requester.h
  example_cpp_smart_card_client_app/src/application.cc
  example_cpp_smart_card_client_app/src/built_in_pin_dialog/built_in_pin_dialog_server.cc
  example_cpp_smart_card_client_app/src/built_in_pin_dialog/built_in_pin_dialog_server.h
  example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge.cc
  example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge.h
  example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge_integration_test_helper.cc
  example_cpp_smart_card_client_app/src/entry_point_emscripten.cc
  example_cpp_smart_card_client_app/src/entry_point_nacl.cc
  example_cpp_smart_card_client_app/src/ui_bridge.cc
  example_cpp_smart_card_client_app/src/ui_bridge.h
  smart_card_connector_app/src/application.cc
  smart_card_connector_app/src/entry_point_emscripten.cc
  smart_card_connector_app/src/entry_point_nacl.cc
  third_party/libusb/webport/src/chrome_usb/api_bridge.cc
  third_party/libusb/webport/src/chrome_usb/api_bridge.h
  third_party/libusb/webport/src/public/libusb_web_port_service.cc
  third_party/libusb/webport/src/public/libusb_web_port_service.h
  third_party/pcsc-lite/naclport/cpp_client/src/google_smart_card_pcsc_lite_client/global.cc
  third_party/pcsc-lite/naclport/cpp_client/src/google_smart_card_pcsc_lite_client/global.h
  third_party/pcsc-lite/naclport/cpp_client/src/pcsc_lite_over_requester.cc
  third_party/pcsc-lite/naclport/cpp_client/src/pcsc_lite_over_requester.h
  third_party/pcsc-lite/naclport/server_clients_management/src/clients_manager.cc
  third_party/pcsc-lite/naclport/server_clients_management/src/clients_manager.h
  third_party/pcsc-lite/naclport/server_clients_management/src/google_smart_card_pcsc_lite_server_clients_management/backend.cc
Labels: refactoring

#437 [build] Tests are built after the main code
  common/js/build/Makefile
  example_cpp_smart_card_client_app/build/Makefile
  third_party/libusb/webport/build/Makefile
  third_party/pcsc-lite/naclport/server_clients_management/build/Makefile
Labels: bug

#443 [build] Specify output JS language version
  common/make/js_building_common.mk
Labels: enhancement

#444 [usb] Add USB-to-JS adaptor and get devices via it
  common/js/src/requesting/request-receiver.js
  third_party/libusb/webport/build/Makefile
  third_party/libusb/webport/src/chrome_usb/api_bridge.h
  third_party/libusb/webport/src/chrome_usb/chrome-usb-backend.js
  third_party/libusb/webport/src/libusb-proxy-data-model.js
  third_party/libusb/webport/src/libusb-proxy-receiver.js
  third_party/libusb/webport/src/libusb-to-chrome-usb-adaptor.js
  third_party/libusb/webport/src/libusb-to-js-api-adaptor.js
  third_party/libusb/webport/src/libusb_js_proxy.cc
  third_party/libusb/webport/src/libusb_js_proxy.h
  third_party/libusb/webport/src/libusb_js_proxy_data_model.cc
  third_party/libusb/webport/src/libusb_js_proxy_data_model.h
  third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
  third_party/libusb/webport/src/libusb_opaque_types.cc
  third_party/libusb/webport/src/libusb_opaque_types.h
  third_party/libusb/webport/src/public/libusb_web_port_service.cc
Labels: enhancement

#445 [usb] Listing devices via WebUSB
  third_party/libusb/webport/src/libusb-proxy-receiver.js
  third_party/libusb/webport/src/libusb-to-webusb-adaptor.js
Labels: enhancement

#446 [style] Call JS constructors with brackets
  smart_card_connector_app/src/background.js
Labels: refactoring

#447 [usb] Keep a map of chrome.usb devices
  third_party/libusb/webport/src/libusb-to-chrome-usb-adaptor.js
Labels: enhancement

#450 [usb] Fix memory leak on close failure
  third_party/libusb/webport/src/libusb_js_proxy.cc
Labels: bug

#448 [usb] Get device configs via new JS proxy
  common/cpp/src/google_smart_card_common/value_conversion.cc
  common/cpp/src/google_smart_card_common/value_conversion.h
  third_party/libusb/webport/src/libusb-proxy-data-model.js
  third_party/libusb/webport/src/libusb-proxy-receiver.js
  third_party/libusb/webport/src/libusb-to-chrome-usb-adaptor.js
  third_party/libusb/webport/src/libusb-to-js-api-adaptor.js
  third_party/libusb/webport/src/libusb_js_proxy.cc
  third_party/libusb/webport/src/libusb_js_proxy_data_model.cc
  third_party/libusb/webport/src/libusb_js_proxy_data_model.h
Labels: enhancement

#449 [usb] Open/close devices via new JS proxy
  third_party/libusb/webport/src/libusb-proxy-receiver.js
  third_party/libusb/webport/src/libusb-to-chrome-usb-adaptor.js
  third_party/libusb/webport/src/libusb-to-js-api-adaptor.js
  third_party/libusb/webport/src/libusb_js_proxy.cc
  third_party/libusb/webport/src/libusb_opaque_types.cc
  third_party/libusb/webport/src/libusb_opaque_types.h
Labels: enhancement

#451 [usb] Claim interface via new JS proxy
  third_party/libusb/webport/src/libusb-proxy-receiver.js
  third_party/libusb/webport/src/libusb-to-chrome-usb-adaptor.js
  third_party/libusb/webport/src/libusb-to-js-api-adaptor.js
  third_party/libusb/webport/src/libusb_js_proxy.cc
Labels: enhancement

#452 [usb] Release interface via new JS proxy
  third_party/libusb/webport/src/libusb-proxy-receiver.js
  third_party/libusb/webport/src/libusb-to-chrome-usb-adaptor.js
  third_party/libusb/webport/src/libusb-to-js-api-adaptor.js
  third_party/libusb/webport/src/libusb_js_proxy.cc
Labels: enhancement

#453 [usb] Reset device via new JS proxy
  third_party/libusb/webport/src/libusb-proxy-receiver.js
  third_party/libusb/webport/src/libusb-to-chrome-usb-adaptor.js
  third_party/libusb/webport/src/libusb-to-js-api-adaptor.js
  third_party/libusb/webport/src/libusb_js_proxy.cc
Labels: enhancement

#454 [usb] Add types for control transfer
  third_party/libusb/webport/src/libusb-proxy-data-model.js
  third_party/libusb/webport/src/libusb-proxy-receiver.js
  third_party/libusb/webport/src/libusb-to-chrome-usb-adaptor.js
  third_party/libusb/webport/src/libusb-to-js-api-adaptor.js
  third_party/libusb/webport/src/libusb_js_proxy_data_model.cc
  third_party/libusb/webport/src/libusb_js_proxy_data_model.h
Labels: enhancement

#455 [usb] Decouple USB destination from chrome.usb
  third_party/libusb/webport/src/usb_transfer_destination.cc
  third_party/libusb/webport/src/usb_transfer_destination.h
Labels: refactoring

#457 [usb] Fix control transfer result
  third_party/libusb/webport/src/libusb_js_proxy.cc
Labels: bug

#458 [usb] Do sync bulk/interrupt transfers via async
  third_party/libusb/webport/src/libusb_js_proxy.cc
  third_party/libusb/webport/src/libusb_js_proxy.h
  third_party/libusb/webport/src/libusb_opaque_types.cc
  third_party/libusb/webport/src/libusb_opaque_types.h
Labels: refactoring

#460 [js] Fix bad "this" in TrustedClientsRegistry
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/trusted-clients-registry.js
Labels: bug

#459 [usb] Use new libusbjs transfer type
  third_party/libusb/webport/src/libusb_js_proxy.cc
  third_party/libusb/webport/src/libusb_js_proxy.h
  third_party/libusb/webport/src/libusb_opaque_types.h
  third_party/libusb/webport/src/usb_transfers_parameters_storage.h
Labels: refactoring

#441 Resolve permission prompt not showing in App mode
  common/js/src/popup-window/popup-opener.js
Labels: bug

#463 [usb] Fix chrome.usb empty output transfer results
  third_party/libusb/webport/src/libusb-to-chrome-usb-adaptor.js
  third_party/libusb/webport/src/libusb_js_proxy.cc
Labels: bug

#461 [usb] JS base for bulk/interrupt transfers
  third_party/libusb/webport/src/libusb-proxy-data-model.js
  third_party/libusb/webport/src/libusb-to-chrome-usb-adaptor.js
  third_party/libusb/webport/src/libusb-to-js-api-adaptor.js
  third_party/libusb/webport/src/libusb_js_proxy_data_model.cc
  third_party/libusb/webport/src/libusb_js_proxy_data_model.h
Labels: enhancement

#464 [usb] Fix synchronous transfer event loop
  third_party/libusb/webport/src/libusb_js_proxy.cc
Labels: bug

#465 [usb] Fix missing transfer completion event
  third_party/libusb/webport/src/libusb_opaque_types.cc
Labels: bug

#466 [usb] Implement transfer timeouts in proxy
  third_party/libusb/webport/src/libusb_opaque_types.cc
  third_party/libusb/webport/src/libusb_opaque_types.h
  third_party/libusb/webport/src/usb_transfers_parameters_storage.cc
  third_party/libusb/webport/src/usb_transfers_parameters_storage.h
Labels: enhancement

#435 [wasm] Minify the Emscripten JS files
  common/make/internal/executable_building_emscripten.mk
Labels: enhancement

#467 [ux] Improve heuristic for spurious USB failures
  smart_card_connector_app/src/window-devices-displaying.js
  third_party/pcsc-lite/naclport/server/src/reader-tracker.js
Labels: enhancement

#468 [usb] Wire up transfers with libusb-to-JS
  third_party/libusb/webport/src/libusb-proxy-receiver.js
  third_party/libusb/webport/src/libusb-to-chrome-usb-adaptor.js
  third_party/libusb/webport/src/libusb_js_proxy.cc
Labels: refactoring

#469 [usb] Fix output transfer length overflow
  third_party/libusb/webport/src/libusb_js_proxy_data_model.h
Labels: bug

#471 [wasm] Fix Emscripten load failure handling
  common/js/src/executable-module/emscripten-module.js
Labels: bug

#472 [usb] Mark LibusbToJsApiAdaptor as abstract
  third_party/libusb/webport/src/libusb-to-js-api-adaptor.js
  third_party/libusb/webport/src/libusb-to-webusb-adaptor.js
Labels: refactoring

#473 [usb] Port loginState hook to new adaptor
  smart_card_connector_app/src/background.js
  third_party/libusb/webport/src/chrome_usb/chrome-login-state-hook-unittest.js
  third_party/libusb/webport/src/chrome_usb/chrome-login-state-hook.js
  third_party/libusb/webport/src/libusb-proxy-hook.js
  third_party/libusb/webport/src/libusb-proxy-receiver.js
  third_party/libusb/webport/src/libusb-to-js-api-adaptor.js
Labels: enhancement

#474 Build JS unit tests for the Connector application
  smart_card_connector_app/build/Makefile
  smart_card_connector_app/build/js_unittests/.gitignore
  smart_card_connector_app/build/js_unittests/Makefile
  test-all.sh
Labels: enhancement

#470 [usb] Delete old chrome.usb integration code
  smart_card_connector_app/src/background.js
  third_party/libusb/webport/build/Makefile
  third_party/libusb/webport/src/chrome_usb/api_bridge.cc
  third_party/libusb/webport/src/chrome_usb/api_bridge.h
  third_party/libusb/webport/src/chrome_usb/api_bridge_interface.h
  third_party/libusb/webport/src/chrome_usb/chrome-login-state-hook-unittest.js
  third_party/libusb/webport/src/chrome_usb/chrome-login-state-hook.js
  third_party/libusb/webport/src/chrome_usb/chrome-usb-backend.js
  third_party/libusb/webport/src/chrome_usb/types.cc
  third_party/libusb/webport/src/chrome_usb/types.h
  third_party/libusb/webport/src/libusb-proxy-receiver.js
  third_party/libusb/webport/src/libusb_js_proxy.cc
  third_party/libusb/webport/src/libusb_js_proxy.h
  third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
  third_party/libusb/webport/src/public/libusb_web_port_service.cc
  third_party/libusb/webport/src/usb_transfer_destination.cc
  third_party/libusb/webport/src/usb_transfer_destination.h
Labels: refactoring

#475 [usb] Compile-time checks for struct field sizes
  common/cpp/src/google_smart_card_common/numeric_conversions.h
  third_party/libusb/webport/src/libusb_js_proxy.cc
  third_party/libusb/webport/src/libusb_js_proxy_data_model.h
Labels: enhancement

#476 [wasm] Use content security policy in extension
  smart_card_connector_app/src/manifest.json.template
Labels: enhancement

#477 [wasm] Specify COOP/COEP when using WebAssembly
  smart_card_connector_app/build/Makefile
  smart_card_connector_app/src/manifest.json.template
Labels: enhancement

#478 [common] Clean up type checks in numeric_conversions.h
  common/cpp/src/google_smart_card_common/numeric_conversions.h
Labels: refactoring

#482 Revert "[wasm] Specify COOP/COEP when using WebAssembly"
  smart_card_connector_app/build/Makefile
  smart_card_connector_app/src/manifest.json.template
Labels: bug

#479 [usb] Implement getConfigurations via WebUSB
  third_party/libusb/webport/src/libusb-to-webusb-adaptor.js
Labels: enhancement
