Repository GoogleChromeLabs/chromeos_smart_card_connector, pull requests merged in 2021-09, with the labels that each got.

#380 Add build-time PACKAGING environment variable
  common/js/src/packaging.js
  common/make/common.mk
  common/make/js_building_common.mk
Labels: enhancement

#381 Enable launch functionality only in the app mode
  smart_card_connector_app/src/background.js
Labels: enhancement

#382 Rename {app_building => packaging}_common.mk
  common/make/packaging_common.mk
  example_cpp_smart_card_client_app/build/Makefile
  example_js_smart_card_client_app/build/Makefile
  smart_card_connector_app/build/Makefile
Labels: refactoring

#384 Avoid exceptions on missing USB API
  third_party/libusb/webport/src/chrome_usb/chrome-usb-backend.js
Labels: enhancement

#385 app/extension conditions in manifest.json.template
  smart_card_connector_app/build/Makefile
  smart_card_connector_app/src/create_app_manifest.py
  smart_card_connector_app/src/manifest.json.template
Labels: enhancement

#386 Differentiate app-/extension-specific permissions
  smart_card_connector_app/src/manifest.json.template
Labels: enhancement

#388 Rename server.js and client.js and corresponding calls
  common/js/src/popup-window/in-popup-main-script.js
  common/js/src/popup-window/popup-opener.js
  example_cpp_smart_card_client_app/src/background.js
  example_cpp_smart_card_client_app/src/built_in_pin_dialog/built-in-pin-dialog-backend.js
  example_cpp_smart_card_client_app/src/built_in_pin_dialog/built-in-pin-dialog-main.js
  example_cpp_smart_card_client_app/src/window.js
  example_js_smart_card_client_app/src/pin-dialog/pin-dialog-main.js
  example_js_smart_card_client_app/src/pin-dialog/pin-dialog-server.js
  smart_card_connector_app/src/background-main-window-managing.js
  smart_card_connector_app/src/window-apps-displaying.js
  smart_card_connector_app/src/window-devices-displaying.js
  smart_card_connector_app/src/window-main.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompt-dialog-main.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittest.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
Labels: refactoring

#387 Fix data passing from background to popup window
  smart_card_connector_app/src/background-main-window-managing.js
  smart_card_connector_app/src/background.js
  smart_card_connector_app/src/window-apps-displaying.js
  smart_card_connector_app/src/window-devices-displaying.js
Labels: enhancement

#391 Fix log collection in Connector's extension mode
  common/js/src/logging/log-buffer.js
  common/js/src/logging/logging.js
  common/js/src/popup-window/popup-opener.js
Labels: enhancement

#395 Fix ArrayBuffer bug in single-message-based comm
  common/js/src/messaging/single-message-based-channel-unittest.js
  common/js/src/messaging/single-message-based-channel.js
Labels: bug

#396 Don't call getBackgroundPage in non-app/extensions
  common/js/src/logging/logging.js
Labels: enhancement

#399 Fix GitHub binary preparation script for packaging
  prepare-binaries-for-github-release.py
Labels: bug

#394 Extend the JS example to use SCardGetStatusChange
  example_js_standalone_smart_card_client_app/background.js
Labels: enhancement

#402 Fix missing import
  common/js/src/packaging.js
Labels: bug

#406 Import CCID 1.4.36
  smart_card_connector_app/build/human_readable_supported_readers.txt
  third_party/ccid/README.google
  third_party/ccid/src/ChangeLog
  third_party/ccid/src/MacOSX/reader.h
  third_party/ccid/src/Makefile.am
  third_party/ccid/src/Makefile.in
  third_party/ccid/src/README.md
  third_party/ccid/src/aclocal.m4
  third_party/ccid/src/config.h.in
  third_party/ccid/src/configure
  third_party/ccid/src/configure.ac
  third_party/ccid/src/contrib/Kobil_mIDentity_switch/Makefile.in
  third_party/ccid/src/contrib/Makefile.in
  third_party/ccid/src/contrib/RSA_SecurID/Makefile.in
  third_party/ccid/src/examples/Makefile.in
  third_party/ccid/src/m4/as-ac-expand.m4
  third_party/ccid/src/m4/ax_pthread.m4
  third_party/ccid/src/readers/Makefile.in
  third_party/ccid/src/readers/supported_readers.txt
  third_party/ccid/src/src/Makefile.am
  third_party/ccid/src/src/Makefile.in
  third_party/ccid/src/src/ccid.c
  third_party/ccid/src/src/ccid.h
  third_party/ccid/src/src/ccid_serial.c
  third_party/ccid/src/src/ccid_usb.c
  third_party/ccid/src/src/commands.c
  third_party/ccid/src/src/debug.c
  third_party/ccid/src/src/ifdhandler.c
  third_party/ccid/src/src/parse.c
  third_party/ccid/src/src/tokenparser.c
  third_party/ccid/src/src/utils.c
  third_party/ccid/webport/include.mk
Labels: enhancement

#407 Import PC/SC-Lite 1.9.3
  third_party/pcsc-lite/README.google
  third_party/pcsc-lite/patches/0001-Fix-IFD_NOT_SUPPORTED.patch
  third_party/pcsc-lite/src/ChangeLog
  third_party/pcsc-lite/src/ChangeLog.git
  third_party/pcsc-lite/src/Makefile.am
  third_party/pcsc-lite/src/Makefile.in
  third_party/pcsc-lite/src/aclocal.m4
  third_party/pcsc-lite/src/bootstrap
  third_party/pcsc-lite/src/config.h.in
  third_party/pcsc-lite/src/configure
  third_party/pcsc-lite/src/configure.ac
  third_party/pcsc-lite/src/doc/Makefile.in
  third_party/pcsc-lite/src/doc/example/Makefile.in
  third_party/pcsc-lite/src/doc/example/pcsc_demo.c
  third_party/pcsc-lite/src/doc/pcscd.8.in
  third_party/pcsc-lite/src/doc/reader.conf.5.in
  third_party/pcsc-lite/src/etc/Makefile.in
  third_party/pcsc-lite/src/etc/pcscd.service.in
  third_party/pcsc-lite/src/m4/as-ac-expand.m4
  third_party/pcsc-lite/src/m4/ax_pthread.m4
  third_party/pcsc-lite/src/m4/libtool.m4
  third_party/pcsc-lite/src/src/Makefile.in
  third_party/pcsc-lite/src/src/PCSC/pcsclite.h
  third_party/pcsc-lite/src/src/PCSC/reader.h
  third_party/pcsc-lite/src/src/debug.c
  third_party/pcsc-lite/src/src/hotplug_libudev.c
  third_party/pcsc-lite/src/src/libpcsclite.pc.in
  third_party/pcsc-lite/src/src/pcscd.h
  third_party/pcsc-lite/src/src/spy/Makefile.am
  third_party/pcsc-lite/src/src/spy/Makefile.in
  third_party/pcsc-lite/src/src/spy/libpcscspy.c
  third_party/pcsc-lite/src/src/spy/pcsc-spy
  third_party/pcsc-lite/src/src/spy/pcsc-spy.pod
  third_party/pcsc-lite/src/src/utils.c
  third_party/pcsc-lite/src/src/utils.h
Labels: enhancement

#408 Add helper for checking string being extension ID
  common/js/src/extension-id-unittest.js
  common/js/src/extension-id.js
Labels: enhancement

#409 Add messaging origin helpers
  common/js/src/messaging/messaging-origin-unittest.js
  common/js/src/messaging/messaging-origin.js
Labels: enhancement

#410 Generalize PC/SC permission prompt
  smart_card_connector_app/src/_locales/en/messages.json
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompt-dialog-main.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompt-dialog.css
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
Labels: enhancement

#411 Use "mimicking" ID for Connector in Debug builds
  smart_card_connector_app/build/Makefile
  smart_card_connector_app/src/create_app_manifest.py
  smart_card_connector_app/src/manifest.json.template
Labels: enhancement

#412 Switch known_client_apps.json to origins
  smart_card_connector_app/src/window-apps-displaying.js
  third_party/pcsc-lite/naclport/server_clients_management/src/known_client_apps.json
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/trusted-clients-registry.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittest.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
Labels: refactoring

#413 Switch PortMessageChannel JS class to origins
  common/js/src/messaging/port-message-channel.js
  smart_card_connector_app/src/background.js
Labels: refactoring

#414 Switch UserPromptingChecker JS class to origins
  common/js/src/messaging/messaging-origin.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/checker.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittest.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
Labels: refactoring

#415 Switch to client_name_for_log in C++ code
  third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js
  third_party/pcsc-lite/naclport/server_clients_management/src/client_request_processor.cc
  third_party/pcsc-lite/naclport/server_clients_management/src/client_request_processor.h
  third_party/pcsc-lite/naclport/server_clients_management/src/clients_manager.cc
  third_party/pcsc-lite/naclport/server_clients_management/src/clients_manager.h
Labels: refactoring
