Repository GoogleChromeLabs/chromeos_smart_card_connector, pull requests merged in 2023-08, with the labels that each got.

#861 Fix flaky teardown errors in bridge-integrationtest
  example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-integrationtest.js
Labels: bug

#860 [JS-to-C++ test] Toolchain-agnostic build interface
  common/integration_testing/build/Makefile
  common/integration_testing/include.mk
  common/integration_testing/src/build_nacl.mk
  example_cpp_smart_card_client_app/build/integration_tests/Makefile
Labels: refactoring

#862 [JS-to-C++ test] run-js-tests can host web server
  common/js_test_runner/run-js-tests.py
Labels: enhancement

#865 [JS-to-C++ test] run-js-tests custom Chrome args
  common/js_test_runner/run-js-tests.py
Labels: enhancement

#868 [JS-to-C++ test] Rename integration_test_pp_module
  common/integration_testing/src/build_nacl.mk
  common/integration_testing/src/entry_point_nacl.cc
Labels: refactoring

#866 [JS-to-C++ test] Turn on tests in Emscripten build
  Makefile
Labels: enhancement

#870 [JS-to-C++ test] Boilerplate for testing Connector
  Makefile
  smart_card_connector_app/build/js_to_cxx_tests/.gitignore
  smart_card_connector_app/build/js_to_cxx_tests/Makefile
  smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Labels: enhancement

#871 [JS-to-C++ test] Make helper SetUp async
  common/integration_testing/build/Makefile
  common/integration_testing/src/google_smart_card_integration_testing/integration_test_helper.cc
  common/integration_testing/src/google_smart_card_integration_testing/integration_test_helper.h
  common/integration_testing/src/google_smart_card_integration_testing/integration_test_service.cc
  common/integration_testing/src/google_smart_card_integration_testing/integration_test_service.h
  example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge_integration_test_helper.cc
Labels: refactoring

#874 [JS-to-C++ test] Make helper TearDown async
  common/integration_testing/src/google_smart_card_integration_testing/integration_test_helper.cc
  common/integration_testing/src/google_smart_card_integration_testing/integration_test_helper.h
  common/integration_testing/src/google_smart_card_integration_testing/integration_test_service.cc
  common/integration_testing/src/google_smart_card_integration_testing/integration_test_service.h
  example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge_integration_test_helper.cc
Labels: refactoring

#876 [JS-to-C++ test] Test PC/SC server startup
  smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Labels: enhancement

#877 [JS-to-C++ test] Increase timeout in Python wrapper
  common/integration_testing/src/build_emscripten.mk
Labels: enhancement

#878 [JS-to-C++ test] Test SCardEstablishContext
  smart_card_connector_app/build/js_to_cxx_tests/Makefile
  smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Labels: enhancement

#879 [JS-to-C++ test] Allow developer manual test debug
  common/integration_testing/src/build_emscripten.mk
  common/js_test_runner/run-js-tests.py
Labels: enhancement

#880 [JS-to-C++ test] Test args of SCardEstablishContext
  smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Labels: enhancement

#881 Refactor TestingGlobalContext callbacks
  common/cpp/src/public/testing_global_context.cc
  common/cpp/src/public/testing_global_context.h
  smart_card_connector_app/src/application_unittest.cc
  smart_card_connector_app/src/testing_smart_card_simulation.cc
  smart_card_connector_app/src/testing_smart_card_simulation.h
Labels: refactoring

#882 Uncommit PC/SC aclocal.m4 and configure
  third_party/pcsc-lite/src/aclocal.m4
  third_party/pcsc-lite/src/configure
Labels: refactoring

#888 Helper for rerouting requests in tests
  common/cpp/src/public/testing_global_context.cc
  common/cpp/src/public/testing_global_context.h
Labels: refactoring

#889 Test stub passes through response error messages
  common/cpp/src/public/testing_global_context.cc
  common/cpp/src/public/testing_global_context.h
Labels: enhancement

#890 TestingSmartCardSimulation owns request receiver
  smart_card_connector_app/src/application_unittest.cc
  smart_card_connector_app/src/testing_smart_card_simulation.cc
  smart_card_connector_app/src/testing_smart_card_simulation.h
Labels: refactoring

#892 [JS-to-C++ test] Pull CCID config file
  smart_card_connector_app/build/js_to_cxx_tests/Makefile
Labels: enhancement

#891 [JS-to-C++ test] Create TestingSmartCardSimulation
  smart_card_connector_app/build/js_to_cxx_tests/Makefile
  smart_card_connector_app/src/application_integration_test_helper.cc
Labels: enhancement

#894 [JS-to-C++ test] Create LibusbProxyReceiver
  smart_card_connector_app/build/js_to_cxx_tests/Makefile
  smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Labels: enhancement

#895 [headers] Include by abs path from libusb/webport/
  third_party/libusb/webport/src/libusb_contexts_storage.cc
  third_party/libusb/webport/src/libusb_contexts_storage.h
  third_party/libusb/webport/src/libusb_error_name.c
  third_party/libusb/webport/src/libusb_js_proxy.cc
  third_party/libusb/webport/src/libusb_js_proxy.h
  third_party/libusb/webport/src/libusb_js_proxy_data_model.cc
  third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
  third_party/libusb/webport/src/libusb_opaque_types.cc
  third_party/libusb/webport/src/libusb_opaque_types.h
  third_party/libusb/webport/src/libusb_tracing_wrapper.cc
  third_party/libusb/webport/src/libusb_tracing_wrapper.h
  third_party/libusb/webport/src/public/libusb_web_port_service.cc
  third_party/libusb/webport/src/usb_transfer_destination.cc
  third_party/libusb/webport/src/usb_transfers_parameters_storage.cc
  third_party/libusb/webport/src/usb_transfers_parameters_storage.h
Labels: refactoring

#896 [headers] Include by abs path from common/integration_testing/
  common/integration_testing/src/entry_point_emscripten.cc
  common/integration_testing/src/entry_point_nacl.cc
  common/integration_testing/src/google_smart_card_integration_testing/integration_test_helper.cc
  common/integration_testing/src/google_smart_card_integration_testing/integration_test_service.cc
  common/integration_testing/src/google_smart_card_integration_testing/integration_test_service.h
  example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge_integration_test_helper.cc
  smart_card_connector_app/src/application_integration_test_helper.cc
Labels: refactoring

#897 [headers] Include by abs path from pcsc-lite/
  smart_card_connector_app/src/application.cc
  smart_card_connector_app/src/application.h
  third_party/pcsc-lite/naclport/common/src/google_smart_card_pcsc_lite_common/pcsc_lite_tracing_wrapper.cc
  third_party/pcsc-lite/naclport/common/src/google_smart_card_pcsc_lite_common/pcsc_lite_tracing_wrapper.h
  third_party/pcsc-lite/naclport/common/src/google_smart_card_pcsc_lite_common/scard_debug_dump.cc
  third_party/pcsc-lite/naclport/common/src/google_smart_card_pcsc_lite_common/scard_structs_serialization.cc
  third_party/pcsc-lite/naclport/cpp_client/src/google_smart_card_pcsc_lite_client/global.cc
  third_party/pcsc-lite/naclport/cpp_client/src/pcsc_lite_over_requester.cc
  third_party/pcsc-lite/naclport/cpp_client/src/pcsc_lite_over_requester.h
  third_party/pcsc-lite/naclport/cpp_demo/src/google_smart_card_pcsc_lite_cpp_demo/demo.cc
  third_party/pcsc-lite/naclport/server/src/public/pcsc_lite_server_web_port_service.cc
  third_party/pcsc-lite/naclport/server/src/server_sockets_manager.cc
  third_party/pcsc-lite/naclport/server/src/winscard_msg_nacl.cc
  third_party/pcsc-lite/naclport/server_clients_management/src/admin_policy_getter.cc
  third_party/pcsc-lite/naclport/server_clients_management/src/client_handles_registry.cc
  third_party/pcsc-lite/naclport/server_clients_management/src/client_request_processor.cc
  third_party/pcsc-lite/naclport/server_clients_management/src/client_request_processor.h
  third_party/pcsc-lite/naclport/server_clients_management/src/clients_manager.cc
  third_party/pcsc-lite/naclport/server_clients_management/src/clients_manager.h
  third_party/pcsc-lite/naclport/server_clients_management/src/google_smart_card_pcsc_lite_server_clients_management/backend.cc
  third_party/pcsc-lite/naclport/server_clients_management/src/google_smart_card_pcsc_lite_server_clients_management/backend.h
  third_party/pcsc-lite/naclport/server_clients_management/src/google_smart_card_pcsc_lite_server_clients_management/ready_message.cc
Labels: refactoring

#898 [headers] Include by abs path from smart_card_connector_app/
  smart_card_connector_app/src/application.cc
  smart_card_connector_app/src/application_integration_test_helper.cc
  smart_card_connector_app/src/entry_point_emscripten.cc
  smart_card_connector_app/src/entry_point_nacl.cc
Labels: refactoring

#899 [JS-to-C++ test] JS side for TestingSmartCardSimulation
  smart_card_connector_app/build/js_to_cxx_tests/Makefile
  smart_card_connector_app/src/pcsc-api-jstocxxtest.js
  smart_card_connector_app/src/testing-smart-card-simulation-libusb-hook.js
Labels: enhancement

#903 [JS unit tests] Fix connector_app test building
  smart_card_connector_app/build/js_unittests/Makefile
Labels: bug

#908 [libusb] Fix outdated comment on chrome.usb
  third_party/libusb/webport/src/libusb_js_proxy.h
Labels: refactoring

#909 [headers] Move files to common/integration_testing/src/public/
  common/integration_testing/build/Makefile
  common/integration_testing/src/entry_point_emscripten.cc
  common/integration_testing/src/entry_point_nacl.cc
  common/integration_testing/src/public/integration-test-controller.js
  common/integration_testing/src/public/integration_test_helper.cc
  common/integration_testing/src/public/integration_test_helper.h
  common/integration_testing/src/public/integration_test_service.cc
  common/integration_testing/src/public/integration_test_service.h
  example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge_integration_test_helper.cc
  smart_card_connector_app/src/application_integration_test_helper.cc
Labels: refactoring

#911 [wasm] Prune unneeded ENVIRONMENT support code
  common/cpp_unit_test_runner/src/build_emscripten.mk
  common/make/internal/executable_building_emscripten.mk
Labels: enhancement

#913 [wasm] Turn off support for non-Chrome browsers
  common/make/internal/executable_building_emscripten.mk
Labels: enhancement

#912 [wasm] Prune code for unneeded Module attributes
  common/js/src/executable-module/emscripten-module.js
  common/make/internal/executable_building_emscripten.mk
Labels: enhancement

#916 [usb] Move chrome-login-state-hook.js
  smart_card_connector_app/src/chrome-login-state-hook-unittest.js
  smart_card_connector_app/src/chrome-login-state-hook.js
Labels: refactoring

#915 [wasm] Drop support for ancient Chrome
  common/make/internal/executable_building_emscripten.mk
Labels: enhancement

#921 [pcsc] Fix crash on shutdown with active client
  smart_card_connector_app/src/application.cc
  smart_card_connector_app/src/application_unittest.cc
  smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Labels: bug

#922 [JS-to-C++ test] Exclude libusb unit tests
  smart_card_connector_app/build/js_to_cxx_tests/Makefile
Labels: enhancement

#923 [JS-to-C++ test] Rename example app's tests
  Makefile
  example_cpp_smart_card_client_app/build/Makefile
  example_cpp_smart_card_client_app/build/js_to_cxx_tests/.gitignore
  example_cpp_smart_card_client_app/build/js_to_cxx_tests/Makefile
Labels: refactoring

#924 [headers] Move files to third_party/pcsc-lite/naclport/common/src/public
  third_party/pcsc-lite/naclport/common/build/Makefile
  third_party/pcsc-lite/naclport/common/src/public/pcsc_lite.h
  third_party/pcsc-lite/naclport/common/src/public/pcsc_lite_tracing_wrapper.cc
  third_party/pcsc-lite/naclport/common/src/public/pcsc_lite_tracing_wrapper.h
  third_party/pcsc-lite/naclport/common/src/public/scard_debug_dump.cc
  third_party/pcsc-lite/naclport/common/src/public/scard_debug_dump.h
  third_party/pcsc-lite/naclport/common/src/public/scard_structs_serialization.cc
  third_party/pcsc-lite/naclport/common/src/public/scard_structs_serialization.h
  third_party/pcsc-lite/naclport/cpp_client/src/google_smart_card_pcsc_lite_client/global.cc
  third_party/pcsc-lite/naclport/cpp_client/src/pcsc_lite_over_requester.cc
  third_party/pcsc-lite/naclport/cpp_client/src/pcsc_lite_over_requester.h
  third_party/pcsc-lite/naclport/cpp_demo/src/google_smart_card_pcsc_lite_cpp_demo/demo.cc
  third_party/pcsc-lite/naclport/server_clients_management/src/client_request_processor.cc
  third_party/pcsc-lite/naclport/server_clients_management/src/client_request_processor.h
Labels: refactoring

#925 [headers] Include by abs path from pcsc-lite cpp_client
  example_cpp_smart_card_client_app/src/application.cc
  example_cpp_smart_card_client_app/src/application.h
  third_party/pcsc-lite/naclport/cpp_client/src/google_smart_card_pcsc_lite_client/global.cc
Labels: refactoring

#927 [ui] Refactor OS warning UI into separate file
  smart_card_connector_app/src/window-main.js
  smart_card_connector_app/src/window-status-displaying.js
Labels: refactoring

#935 [js style] Fix missing semicolons
  common/js/src/messaging/message-channel-pool.js
  common/js/src/messaging/single-message-based-channel-unittest.js
  smart_card_connector_app/src/chrome-api-jstocxxtest.js
  smart_card_connector_app/src/chrome-api-provider.js
  smart_card_connector_app/src/testing-smart-card-simulation-libusb-hook.js
  third_party/pcsc-lite/naclport/server/src/reader-tracker.js
Labels: refactoring

#931 [ui] Show warning in UI if application crashed
  smart_card_connector_app/src/_locales/en/messages.json
  smart_card_connector_app/src/background.js
  smart_card_connector_app/src/window-status-displaying.js
  smart_card_connector_app/src/window.css
  smart_card_connector_app/src/window.html
Labels: enhancement

#932 [policy] Fix crash if policy loaded after disposal
  third_party/pcsc-lite/naclport/server_clients_management/src/admin-policy-service.js
Labels: enhancement

#933 [wasm] Improve handling of crashes
  common/js/src/executable-module/emscripten-module.js
Labels: enhancement

#934 [js style] Fix extra semicolons
  common/js/src/logging/log-buffer.js
  common/js/src/messaging/message-channel-pair.js
  common/js/src/requesting/requester-unittest.js
  smart_card_connector_app/src/chrome-api-provider.js
  smart_card_connector_app/src/chrome-login-state-hook-unittest.js
  smart_card_connector_app/src/smart-card-filter-libusb-hook-unittest.js
Labels: refactoring

#936 Increase timeouts for CI jobs
  .github/workflows/makefile.yml
Labels: bug

#942 [js style] Use aliases where already defined
  common/js/src/messaging/port-message-channel-unittest.js
  common/js/src/messaging/single-message-based-channel-unittest.js
  common/js/src/requesting/requester-unittest.js
Labels: refactoring

#944 [JS-to-C++ test] Tear down BridgeBackend
  example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-integrationtest.js
Labels: enhancement

#938 [js style] Fix unreachable code
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittest.js
Labels: refactoring

#939 [js style] Fix no-prototype-builtins
  common/js/src/logging/crash-loop-detection-unittest.js
  common/js/src/logging/crash-loop-detection.js
  common/js/src/nacl-module/nacl-module.js
Labels: enhancement

#949 [pcsc] Fix flaky shutdown
  third_party/pcsc-lite/naclport/server/src/public/pcsc_lite_server_web_port_service.cc
  third_party/pcsc-lite/src/src/hotplug_libusb.c
Labels: enhancement

#943 [js style] Drop unused vars
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompt-dialog-main.js
Labels: refactoring

#952 [JS-to-C++ test] Shut down request receiver
  common/integration_testing/src/public/integration_test_service.cc
Labels: bug

#953 [JS-to-C++ test] Print full JS logs on failure
  common/js_test_runner/run-js-tests.py
Labels: enhancement

#956 [js style] Use brackets when calling constructors
  common/integration_testing/src/public/integration-test-controller.js
  common/js/src/container-helpers-unittest.js
  common/js/src/deferred-processor.js
  common/js/src/executable-module/emscripten-module.js
  common/js/src/i18n-unittest.js
  common/js/src/json.js
  common/js/src/logging/crash-loop-detection-unittest.js
  common/js/src/logging/logging.js
  common/js/src/messaging/message-channel-pool.js
  common/js/src/requesting/requester-unittest.js
  common/js/src/requesting/requester.js
  smart_card_connector_app/src/chrome-login-state-hook-unittest.js
  third_party/pcsc-lite/naclport/cpp_client/src/nacl-client-backend.js
  third_party/pcsc-lite/naclport/server/src/reader-tracker.js
  third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/managed-registry.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/policy-or-prompting-permissions-checker.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/trusted-clients-registry.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittest.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
Labels: refactoring

#957 [js style] Use const when possible
  common/js/src/container-helpers.js
  common/js/src/i18n.js
  common/js/src/messaging/message-channel-pair.js
  common/js/src/messaging/message-channel-pool.js
  common/js/src/messaging/mock-port.js
  common/js/src/messaging/port-message-channel-unittest.js
  common/js/src/messaging/single-message-based-channel-unittest.js
  smart_card_connector_app/src/chrome-api-jstocxxtest.js
  smart_card_connector_app/src/chrome-api-provider.js
  smart_card_connector_app/src/window-devices-displaying.js
  third_party/pcsc-lite/naclport/server/src/reader-tracker.js
Labels: refactoring

#958 [js style] Fix excessively long lines
  common/js/src/logging/logging.js
  example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-backend.js
  third_party/pcsc-lite/naclport/js_client/src/reader-tracker-through-pcsc-api.js
  third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/trusted-clients-registry.js
Labels: refactoring

#959 [js style] More semicolon fixes
  smart_card_connector_app/src/chrome-api-jstocxxtest.js
  third_party/libusb/webport/src/libusb-to-webusb-adaptor.js
Labels: refactoring

#962 [js style] Add basic ESLint config
  .eslintrc.yml
Labels: enhancement

#963 [js style] More ESLint rules
  .eslintrc.yml
Labels: enhancement

#960 [js style] Fix excessive return tag
  common/js/src/promise-helpers.js
Labels: refactoring

#964 Update Emscripten to 3.1.45
  env/constants.sh
Labels: enhancement

#966 [js style] Install NPM into env/
  env/.gitignore
  env/initialize.sh
Labels: enhancement

#971 [headers] Include by abs path from pcsc-lite cpp_demo
  third_party/pcsc-lite/naclport/cpp_demo/src/google_smart_card_pcsc_lite_cpp_demo/demo.cc
Labels: refactoring

#967 [js style] Install ESLint into env/
  env/initialize.sh
Labels: enhancement

#970 Refactor logic for finding sources-to-be-linted
  format-code.sh
  scripts/internal/find-files-for-linting.sh
Labels: refactoring

#974 [JS-to-C++ test] Test SCardIsValidContext
  smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Labels: enhancement

#968 [js style] Script for running ESLint
  scripts/eslint.sh
Labels: enhancement

#978 [scripts] Rewrite find-files-for-linting in Python
  format-code.sh
  scripts/eslint.sh
  scripts/internal/find-files-for-linting.py
  scripts/internal/find-files-for-linting.sh
Labels: refactoring

#979 [scripts] Pass base gitref to find-files-for-linting
  scripts/internal/find-files-for-linting.py
Labels: enhancement

#980 [scripts] Ignore third-party code from linting
  scripts/internal/find-files-for-linting.py
Labels: enhancement

#981 [js style] ESLint script accepts base ref and fix
  scripts/eslint.py
  scripts/eslint.sh
Labels: enhancement

#984 [ci] Skip JS targets in sanitizer/coverage builds
  Makefile
Labels: enhancement

#89 Handle more Xhrio failures
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/trusted-clients-registry.js
Labels: bug

#985 [ci] Skip python3_venv and chromedriver in analysis
  env/initialize.sh
Labels: enhancement

#988 [JS-to-C++ test] Test SCardCancel success
  smart_card_connector_app/src/application_unittest.cc
  smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Labels: enhancement

#989 [chrome-api-jstocxxtest] Refactor report result check
  smart_card_connector_app/src/chrome-api-jstocxxtest.js
  smart_card_connector_app/src/mock-chrome-api.js
Labels: refactoring

#987 [JS-to-C++ test] Test SCardGetStatusChange cards
  smart_card_connector_app/src/pcsc-api-jstocxxtest.js
  smart_card_connector_app/src/testing-smart-card-simulation-constants.js
Labels: enhancement

#992 [headers] Move cpp_demo to public
  example_cpp_smart_card_client_app/src/application.cc
  third_party/pcsc-lite/naclport/cpp_demo/build/Makefile
  third_party/pcsc-lite/naclport/cpp_demo/src/public/demo.cc
  third_party/pcsc-lite/naclport/cpp_demo/src/public/demo.h
Labels: refactoring

#994 [js style] Enable no-invalid-this linter
  .eslintrc.yml
  common/js/src/requesting/requester.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/policy-or-prompting-permissions-checker.js
  third_party/pcsc-lite/naclport/server_clients_management/src/server-request-handler.js
Labels: enhancement

#990 [JS-to-C++] Test malformed requests
  smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Labels: enhancement

#969 [js style] Execute ESLint in CI runs
  .github/actions/build-dependencies-installation/action.yml
  .github/workflows/makefile.yml
Labels: enhancement

#995 [js style] Enable more ESLint suggestion checks
  .eslintrc.yml
Labels: enhancement

#997 [js style] PRs touching linting are checked on all
  .github/workflows/makefile.yml
Labels: enhancement
