Repository GoogleChromeLabs/chromeos_smart_card_connector, pull requests merged in 2023-09, with the labels that each got.

#999 [js style] Enable ESLint guard-for-in
  .eslintrc.yml
  common/js/src/logging/crash-loop-detection-unittest.js
Labels: enhancement

#1000 [makefile] Drop test targets in child makefiles
  common/cpp/build/Makefile
  common/js/build/Makefile
  example_cpp_smart_card_client_app/build/Makefile
  smart_card_connector_app/build/Makefile
  smart_card_connector_app/build/executable_module/Makefile
  third_party/libusb/webport/build/Makefile
  third_party/pcsc-lite/naclport/server_clients_management/build/Makefile
Labels: bug

#1005 Fix clean-all.sh for pnacl
  clean-all.sh
Labels: bug

#1023 Choose latest Chromedriver per Chrome milestone
  env/initialize.sh
Labels: bug

#1022 [PC/SC test] Don't assert handle/context non-zero
  smart_card_connector_app/src/application_unittest.cc
Labels: enhancement

#1020 [JS-to-C++ test] Test SCardConnect success
  smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Labels: enhancement

#1019 [JS-to-C++ test] Test SCardCancel errors
  smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Labels: enhancement

#1028 [JS-to-C++ test] Fix flaky USB transfer exception
  smart_card_connector_app/src/testing_smart_card_simulation.cc
Labels: bug

#1024 [style] format-code in Python, supports --base
  format-code.sh
  scripts/format-code.py
Labels: enhancement

#1025 [style] Reapply clang-format
  common/cpp/src/public/logging/syslog/syslog.h
  common/js/src/deferred-processor.js
  common/js/src/extension-id.js
  common/js/src/packaging.js
  third_party/pcsc-lite/naclport/server/src/readerfactory_nacl.cc
  third_party/pcsc-lite/naclport/server/src/sys/un.h
Labels: refactoring

#1029 [JS-to-C++ test] Boilerplate for //common/js tests
  Makefile
  common/integration_testing/include.mk
  common/js/build/js_to_cxx_tests/.gitignore
  common/js/build/js_to_cxx_tests/Makefile
  common/js/build/unittests/Makefile
  common/js/include.mk
  common/js/src/executable-module/executable-module-jstocxxtest.js
Labels: enhancement

#88 Trusted clients registry unit tests
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/trusted-clients-registry-unittest.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/trusted-clients-registry.js
Labels: enhancement

#1026 [JS-to-C++ test] Test SCardDisconnect success
  smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Labels: enhancement

#1034 [ci] Reduce apt/git log spam, uprev github actions
  .github/actions/build-dependencies-installation/action.yml
  .github/workflows/makefile.yml
Labels: enhancement

#1027 [JS-to-C++ test] Test SCardReconnect success
  smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Labels: enhancement

#1039 [js] Use JS 2020, don't transpile to JS 2012
  common/make/js_building_common.mk
Labels: enhancement

#1037 [refactor] Move nacl-module*.js
  common/js/src/executable-module/nacl-module-log-messages-receiver.js
  common/js/src/executable-module/nacl-module-messaging-channel.js
  common/js/src/executable-module/nacl-module.js
Labels: refactoring

#1043 [style] format-code check-only mode
  scripts/format-code.py
Labels: enhancement

#1045 [style] Import find-files-for-linting Python code
  scripts/eslint.py
  scripts/format-code.py
  scripts/internal/.gitignore
  scripts/internal/find_files_for_linting.py
Labels: refactoring

#1044 [js style] Rename fns to debugDump{Full,Sanitized}
  common/js/src/executable-module/emscripten-module.js
  common/js/src/executable-module/nacl-module-messaging-channel.js
  common/js/src/logging/debug-dump-unittest.js
  common/js/src/logging/debug-dump.js
  common/js/src/messaging/common.js
  common/js/src/messaging/port-message-channel.js
  common/js/src/messaging/single-message-based-channel.js
  common/js/src/object-helpers.js
  common/js/src/popup-window/in-popup-main-script.js
  common/js/src/popup-window/popup-opener.js
  common/js/src/requesting/remote-call-message.js
  common/js/src/requesting/request-receiver.js
  common/js/src/requesting/requester.js
  example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-backend.js
  smart_card_connector_app/src/chrome-api-provider.js
  smart_card_connector_app/src/pcsc-api-jstocxxtest.js
  smart_card_connector_app/src/window-apps-displaying.js
  smart_card_connector_app/src/window-devices-displaying.js
  third_party/libusb/webport/src/libusb-proxy-receiver.js
  third_party/libusb/webport/src/libusb-to-webusb-adaptor.js
  third_party/pcsc-lite/naclport/cpp_client/src/nacl-client-backend.js
  third_party/pcsc-lite/naclport/js_client/src/api.js
  third_party/pcsc-lite/naclport/js_client/src/reader-tracker-through-pcsc-api.js
  third_party/pcsc-lite/naclport/js_demo/src/demo.js
  third_party/pcsc-lite/naclport/server/src/reader-tracker.js
  third_party/pcsc-lite/naclport/server_clients_management/src/admin-policy-service.js
  third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/managed-registry.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/policy-or-prompting-permissions-checker.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/trusted-clients-registry.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
  third_party/pcsc-lite/naclport/server_clients_management/src/server-request-handler.js
Labels: refactoring

#1042 [js style] Add eslint-plugin-no-floating-promise
  .eslintrc.yml
  env/initialize.sh
  scripts/eslint.py
  smart_card_connector_app/src/chrome-api-jstocxxtest.js
  smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Labels: enhancement

#1041 [wasm] Force-kill threads and workers on disposal
  common/js/src/executable-module/emscripten-module-js-epilog.js.inc
  common/js/src/executable-module/emscripten-module.js
  common/make/internal/executable_building_emscripten.mk
Labels: enhancement

#1030 [JS-to-C++ test] Test SCardStatus success
  smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Labels: enhancement

#1048 JS Requester handles exceptions correctly
  common/js/src/requesting/requester-unittest.js
  common/js/src/requesting/requester.js
Labels: enhancement

#1047 [JS-to-C++ test] Suppress reader_init warnings
  smart_card_connector_app/build/js_to_cxx_tests/Makefile
  smart_card_connector_app/src/chrome-api-jstocxxtest.js
  smart_card_connector_app/src/pcsc-api-jstocxxtest.js
  third_party/pcsc-lite/naclport/server/src/reader-tracker.js
Labels: enhancement

#1052 [js style] Disable semi-spacing ESLint
  .eslintrc.yml
Labels: bug

#1046 [JS-to-C++ test] Test SCardGetAttrib
  smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Labels: enhancement

#1049 [js promise] Use Thenable in type annotations
  common/integration_testing/src/public/integration-test-controller.js
  common/js/src/deferred-processor.js
  common/js/src/executable-module/executable-module.js
  common/js/src/json.js
  common/js/src/messaging/single-message-based-channel-unittest.js
  common/js/src/popup-window/popup-opener.js
  common/js/src/promise-helpers.js
  common/js/src/requesting/request-receiver.js
  common/js/src/requesting/requester.js
  example_cpp_smart_card_client_app/src/built_in_pin_dialog/built-in-pin-dialog-backend.js
  example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-backend.js
  example_js_smart_card_client_app/src/pin-dialog/pin-dialog-server.js
  smart_card_connector_app/src/chrome-api-provider.js
  smart_card_connector_app/src/chrome-login-state-hook-unittest.js
  smart_card_connector_app/src/testing-smart-card-simulation-libusb-hook.js
  smart_card_connector_app/src/window-apps-displaying.js
  third_party/libusb/webport/src/libusb-proxy-receiver.js
  third_party/pcsc-lite/naclport/cpp_client/src/nacl-client-backend.js
  third_party/pcsc-lite/naclport/js_client/src/api.js
  third_party/pcsc-lite/naclport/js_client/src/reader-tracker-through-pcsc-api.js
  third_party/pcsc-lite/naclport/server/src/reader-tracker.js
  third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/managed-registry.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/permissions-checker.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/trusted-clients-registry-unittest.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/trusted-clients-registry.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittest.js
  third_party/pcsc-lite/naclport/server_clients_management/src/readiness-tracker.js
  third_party/pcsc-lite/naclport/server_clients_management/src/server-request-handler.js
Labels: refactoring

#1054 [makefile] Drop static lib constants
  common/cpp/build/Makefile
  common/cpp/include.mk
  common/integration_testing/src/build_emscripten.mk
  common/integration_testing/src/build_nacl.mk
  common/js/build/js_to_cxx_tests/Makefile
  example_cpp_smart_card_client_app/build/executable_module/Makefile
  example_cpp_smart_card_client_app/build/js_to_cxx_tests/Makefile
  smart_card_connector_app/build/executable_module/Makefile
  smart_card_connector_app/build/js_to_cxx_tests/Makefile
  third_party/ccid/webport/build/Makefile
  third_party/ccid/webport/include.mk
  third_party/libusb/webport/build/Makefile
  third_party/libusb/webport/include.mk
  third_party/pcsc-lite/naclport/common/build/Makefile
  third_party/pcsc-lite/naclport/common/include.mk
  third_party/pcsc-lite/naclport/cpp_client/build/Makefile
  third_party/pcsc-lite/naclport/cpp_client/include.mk
  third_party/pcsc-lite/naclport/cpp_demo/build/Makefile
  third_party/pcsc-lite/naclport/cpp_demo/include.mk
  third_party/pcsc-lite/naclport/server/build/Makefile
  third_party/pcsc-lite/naclport/server/include.mk
  third_party/pcsc-lite/naclport/server_clients_management/build/Makefile
  third_party/pcsc-lite/naclport/server_clients_management/include.mk
Labels: refactoring

#1055 [js style] await instead of returning promise
  third_party/libusb/webport/src/libusb-proxy-hook.js
  third_party/libusb/webport/src/libusb-to-chrome-usb-adaptor.js
  third_party/libusb/webport/src/libusb-to-webusb-adaptor.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
Labels: enhancement

#1056 [js promise] Move promisify to common
  common/js/src/promisify-extension-api.js
  third_party/libusb/webport/src/libusb-to-chrome-usb-adaptor.js
Labels: refactoring

#1053 [JS-to-C++ test] Test crashes
  common/cpp/src/logging_integration_test_helper.cc
  common/js/build/js_to_cxx_tests/Makefile
  common/js/src/executable-module/executable-module-jstocxxtest.js
Labels: enhancement

#1057 JS Requester handles disposal-and-exception-while-sending
  common/js/src/requesting/requester-unittest.js
  common/js/src/requesting/requester.js
Labels: bug

#1058 [JS-to-C++ test] Test crash with active PC/SC client
  common/js/src/async-asserts.js
  common/js/src/requesting/requester-unittest.js
  smart_card_connector_app/build/js_to_cxx_tests/Makefile
  smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Labels: enhancement

#1060 [refactoring] Rename _nacl to _webport in server
  third_party/pcsc-lite/naclport/server/build/Makefile
  third_party/pcsc-lite/naclport/server/src/auth_webport.cc
  third_party/pcsc-lite/naclport/server/src/dyn_webport.cc
  third_party/pcsc-lite/naclport/server/src/pcscdaemon_webport.cc
  third_party/pcsc-lite/naclport/server/src/readerfactory_webport.cc
  third_party/pcsc-lite/naclport/server/src/sys_webport.cc
  third_party/pcsc-lite/naclport/server/src/unistd_webport.cc
  third_party/pcsc-lite/naclport/server/src/winscard_msg_webport.cc
Labels: refactoring

#1061 Fix permissions for find_files_for_linting.py
  scripts/internal/find_files_for_linting.py
Labels: bug

#1059 [JS tests] Unify the used Chrome binary path
  common/integration_testing/src/build_emscripten.mk
  common/js_test_runner/run-js-tests.py
  common/make/js_building_common.mk
Labels: enhancement

#1062 [logging] Downgrade warning in server-request-handler.js
  third_party/pcsc-lite/naclport/server_clients_management/src/server-request-handler.js
Labels: enhancement

#1063 [js promise] Use promisify in UserPromptingChecker
  common/js/src/promisify-extension-api.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
Labels: refactoring

#1064 [js promise] Use promisify in CrashLoopDetection
  common/js/src/logging/crash-loop-detection.js
Labels: refactoring

#1068 [PC/SC test] Add more SCardGetAttrib tests
  smart_card_connector_app/src/application_unittest.cc
Labels: enhancement

#1072 [PC/SC test] More EndTransaction errors
  smart_card_connector_app/src/application_unittest.cc
Labels: enhancement

#1070 [JS-to-C++ test] Test SCardConnect protocol mismatch
  smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Labels: enhancement

#1081 [PC/SC test] SetAttrib success and more error cases
  smart_card_connector_app/src/application_unittest.cc
Labels: enhancement

#1079 Cherry-pick CCID fix for 10-min hang on shutdown
  third_party/ccid/patches/0004-Fix-InterruptStop-if-called-before-InterruptRead.patch
  third_party/ccid/src/src/ccid_usb.c
Labels: bug

#1080 Test for 10-minute shutdown hang
  smart_card_connector_app/src/application_unittest.cc
Labels: enhancement

#1077 [chrome-api-jstocxxtest] Move constants and group tests
  smart_card_connector_app/src/chrome-api-jstocxxtest.js
  smart_card_connector_app/src/testing-constants.js
  smart_card_connector_app/src/testing-smart-card-simulation-constants.js
  third_party/pcsc-lite/naclport/common/src/constants.js
Labels: refactoring

#1082 [PC/SC test] Simulate Yubikey 4C
  smart_card_connector_app/src/application_unittest.cc
  smart_card_connector_app/src/testing_smart_card_simulation.cc
  smart_card_connector_app/src/testing_smart_card_simulation.h
Labels: enhancement
