Repository GoogleChromeLabs/chromeos_smart_card_connector, pull requests merged in 2023-07, with the labels that each got.

#819 Don't rely on DEPS and dependency.mk for build
  common/cpp/dependency.mk
  common/integration_testing/dependency.mk
  common/tests_runner/build.mk
  example_cpp_smart_card_client_app/build/executable_module/Makefile
  example_cpp_smart_card_client_app/build/integration_tests/Makefile
  smart_card_connector_app/build/executable_module/Makefile
  third_party/ccid/webport/dependency.mk
  third_party/libusb/webport/dependency.mk
  third_party/pcsc-lite/naclport/common/dependency.mk
  third_party/pcsc-lite/naclport/cpp_client/dependency.mk
  third_party/pcsc-lite/naclport/cpp_demo/dependency.mk
  third_party/pcsc-lite/naclport/server/dependency.mk
  third_party/pcsc-lite/naclport/server_clients_management/dependency.mk
Labels: enhancement

#820 Uprev PC/SC-Lite to 2.0.0
  third_party/pcsc-lite/README.google
  third_party/pcsc-lite/naclport/server/build/Makefile
  third_party/pcsc-lite/naclport/server/src/dyn_nacl.cc
  third_party/pcsc-lite/naclport/server/src/public/pcsc_lite_server_web_port_service.cc
  third_party/pcsc-lite/src/ChangeLog
  third_party/pcsc-lite/src/ChangeLog.git
  third_party/pcsc-lite/src/Makefile.in
  third_party/pcsc-lite/src/README
  third_party/pcsc-lite/src/SECURITY
  third_party/pcsc-lite/src/config.h.in
  third_party/pcsc-lite/src/configure
  third_party/pcsc-lite/src/configure.ac
  third_party/pcsc-lite/src/doc/doxygen.conf.in
  third_party/pcsc-lite/src/ltmain.sh
  third_party/pcsc-lite/src/src/PCSC/debuglog.h
  third_party/pcsc-lite/src/src/PCSC/ifdhandler.h
  third_party/pcsc-lite/src/src/PCSC/pcsclite.h.in
  third_party/pcsc-lite/src/src/PCSC/reader.h
  third_party/pcsc-lite/src/src/README_INTERNALS.txt
  third_party/pcsc-lite/src/src/atrhandler.c
  third_party/pcsc-lite/src/src/auth.c
  third_party/pcsc-lite/src/src/debug.c
  third_party/pcsc-lite/src/src/debuglog.c
  third_party/pcsc-lite/src/src/dyn_generic.h
  third_party/pcsc-lite/src/src/dyn_hpux.c
  third_party/pcsc-lite/src/src/dyn_macosx.c
  third_party/pcsc-lite/src/src/dyn_unix.c
  third_party/pcsc-lite/src/src/eventhandler.c
  third_party/pcsc-lite/src/src/hotplug.h
  third_party/pcsc-lite/src/src/hotplug_generic.c
  third_party/pcsc-lite/src/src/hotplug_libudev.c
  third_party/pcsc-lite/src/src/hotplug_libusb.c
  third_party/pcsc-lite/src/src/hotplug_macosx.c
  third_party/pcsc-lite/src/src/ifdwrapper.c
  third_party/pcsc-lite/src/src/pcscdaemon.c
  third_party/pcsc-lite/src/src/readerfactory.c
  third_party/pcsc-lite/src/src/spy/pcsc-spy
  third_party/pcsc-lite/src/src/sys_generic.h
  third_party/pcsc-lite/src/src/sys_unix.c
  third_party/pcsc-lite/src/src/winscard.c
  third_party/pcsc-lite/src/src/winscard_clnt.c
  third_party/pcsc-lite/src/src/winscard_msg.c
  third_party/pcsc-lite/src/src/winscard_msg_srv.c
  third_party/pcsc-lite/src/src/winscard_svc.c
Labels: enhancement

#825 Migrate Checker to ES6 class
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/checker.js
Labels: refactoring

#826 Rename Checker to PolicyOrPromptingPermissionsChecker
  third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/policy-or-prompting-permissions-checker.js
Labels: refactoring

#827 Add abstract PermissionsChecker interface
  third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/permissions-checker.js
  third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/policy-or-prompting-permissions-checker.js
Labels: refactoring

#828 Add test injector for PermissionsChecker
  third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js
Labels: enhancement

#829 Yet another magic sleep tweak for ASan+Debug tests
  .github/workflows/makefile.yml
  third_party/pcsc-lite/naclport/server/src/public/pcsc_lite_server_web_port_service.cc
Labels: enhancement

#830 Pass Promise instead of ReadinessTracker
  smart_card_connector_app/src/background.js
  third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js
  third_party/pcsc-lite/naclport/server_clients_management/src/server-request-handler.js
Labels: refactoring

#831 Implement smoke test for ClientHandler
  third_party/pcsc-lite/naclport/server_clients_management/build/js_unittests/Makefile
  third_party/pcsc-lite/naclport/server_clients_management/src/client-handler-unittest.js
Labels: enhancement

#834 Switch to new Chromedriver download URLs
  env/initialize.sh
Labels: bug

#824 Fix dispose called on null during ClientHandler disposal
  third_party/pcsc-lite/naclport/server_clients_management/src/client-handler-unittest.js
  third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js
  third_party/pcsc-lite/naclport/server_clients_management/src/server-request-handler.js
Labels: bug

#835 Downgrade warning logs for ReaderTracker removal
  third_party/pcsc-lite/naclport/js_client/src/reader-tracker-through-pcsc-api.js
Labels: enhancement

#839 Connector requires ChromeOS >=81
  smart_card_connector_app/src/manifest.json.template
Labels: enhancement

#841 Fixup instead of crashing on incorrect ATR size
  third_party/pcsc-lite/naclport/common/src/google_smart_card_pcsc_lite_common/scard_structs_serialization.cc
Labels: bug

#844 Escape test function names to prevent minification
  common/js/src/i18n-unittest.js
  common/js/src/logging/crash-loop-detection-unittest.js
  third_party/libusb/webport/src/chrome_usb/chrome-login-state-hook-unittest.js
Labels: enhancement

#847 Use "ChromeOS" spelling in code and docs
  README.md
  docs/building.md
  docs/connector-app-api.md
  docs/index-developer.md
  docs/index-third-party-application-developer.md
  docs/running-on-desktop.md
  docs/updating-ccid.md
  docs/updating-pcsc-lite.md
  example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-backend.js
  smart_card_connector_app/src/_locales/en/messages.json
  smart_card_connector_app/src/background.js
  smart_card_connector_app/src/chrome-api-provider.js
  smart_card_connector_app/src/window-main.js
  third_party/libusb/webport/src/chrome_usb/chrome-login-state-hook.js
  third_party/pcsc-lite/naclport/server/README.rst
Labels: enhancement

#848 Unit-test libusb_get_active_config_descriptor
  third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
Labels: enhancement

#843 Ignore non-smart-card USB interfaces
  smart_card_connector_app/src/background.js
  smart_card_connector_app/src/smart-card-filter-libusb-hook-unittest.js
  smart_card_connector_app/src/smart-card-filter-libusb-hook.js
  third_party/libusb/webport/src/libusb_js_proxy.cc
  third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
Labels: enhancement

#850 Cherry-pick upstream CCID fix for null-deref
  third_party/ccid/patches/0003-Check-num_altsetting-before-dereffing-altsetting.patch
  third_party/ccid/src/src/ccid_usb.c
Labels: bug

#857 Simulate Dell Smart Card Reader Keyboard in tests
  smart_card_connector_app/src/testing_smart_card_simulation.cc
  smart_card_connector_app/src/testing_smart_card_simulation.h
Labels: enhancement

#854 Add PC/SC test running with every simulated reader
  smart_card_connector_app/src/application_unittest.cc
Labels: enhancement

#858 [CI] Don't try posting comments in PRs in forks
  .github/workflows/makefile.yml
Labels: enhancement
